language: go
go:
  - 1.8.x
  - 1.9.x
  - 1.10.x
  - 1.11.x
  - 1.12.x
  - 1.x

os:
  - linux
  - osx

matrix:
  include:
    - os: linux
      addons:
        apt:
          packages:
            - libnss3-dev
    - os: osx
      osx_image: xcode9.1 # OS X 10.12 w/ Xcode 9.1
